'OHRRPGCE - b2m.bi
'(C) Copyright 1997-2006 James Paige and Hamster Republic Productions
'Please read LICENSE.txt for GPL License details and disclaimer of liability
'See README.txt for code docs and apologies for crappyness of this code ;)
'Auto-generated by MAKEBI from b2m.bas

#IFNDEF B2M_BI
#DEFINE B2M_BI

declare sub debug (s$)
declare function isfile (n$) as integer

#ENDIF
