'OHRRPGCE - menus.bi
'(C) Copyright 1997-2006 James Paige and Hamster Republic Productions
'Please read LICENSE.txt for GPL License details and disclaimer of liability
'See README.txt for code docs and apologies for crappyness of this code ;)
'Auto-generated by MAKEBI from menus.bas

#IFNDEF MENUS_BI
#DEFINE MENUS_BI

declare sub editmenus
declare sub vehicles
declare sub gendata ()
declare subcsr = 0
declare sub importsong ()
declare sub importsfx ()

#ENDIF
