'OHRRPGCE - menus.bi
'(C) Copyright 1997-2006 James Paige and Hamster Republic Productions
'Please read LICENSE.txt for GPL License details and disclaimer of liability
'See README.txt for code docs and apologies for crappyness of this code ;)
'Auto-generated by MAKEBI from menus.bas

#IFNDEF MENUS_BI
#DEFINE MENUS_BI

declare sub editmenus
declare sub vehicles
declare sub gendata ()
declare subcsr = 0
declare subm$(0) = "previous menu"
declare subm$(1) = "new-game script: " + scriptname$(general(41), "plotscr.lst")
declare subm$(2) = "game-over script: " + scriptname$(general(42), "plotscr.lst")
declare subm$(3) = "load-game script: " + scriptname$(general(57), "plotscr.lst")
declare sub importsong ()
declare submenu$(0) = "export " + ext$ + " file"
declare submenu$(1) = "export .bam fallback file"
declare submenu$(2) = "cancel"
declare sub importsfx ()

#ENDIF
