'OHRRPGCE - miditest.bi
'(C) Copyright 1997-2020 James Paige, Ralph Versteegen, and Hamster Republic Productions
'Please read LICENSE.txt for GPL License details and disclaimer of liability
'Auto-generated by MAKEBI from miditest.bas

#IFNDEF MIDITEST_BI
#DEFINE MIDITEST_BI

declare function openmidi() as integer
declare function closemidi() as integer
declare function shortmidi(event as ubyte, a as ubyte, b as ubyte) as integer

#ENDIF
