'OHRRPGCE - music_nativea.bi
'(C) Copyright 1997-2006 James Paige and Hamster Republic Productions
'Please read LICENSE.txt for GPL License details and disclaimer of liability
'See README.txt for code docs and apologies for crappyness of this code ;)
'Auto-generated by MAKEBI from music_nativea.bas

#IFNDEF MUSIC_NATIVEA_BI
#DEFINE MUSIC_NATIVEA_BI


#ENDIF
