'OHRRPGCE - verprint.bi
'(C) Copyright 1997-2006 James Paige and Hamster Republic Productions
'Please read LICENSE.txt for GPL License details and disclaimer of liability
'See README.txt for code docs and apologies for crappyness of this code ;)
'Auto-generated by MAKEBI from verprint.bas

#IFNDEF VERPRINT_BI
#DEFINE VERPRINT_BI

declare function datetag$

#ENDIF
